#!/bin/bash

cd gl/2.1/function
rm ../opengl2.1.h

for F in *
do
  echo "" >> ../opengl2.1.h
  echo "/** @see $F */" >> ../opengl2.1.h
  egrep "$F\(" ../../../../list/gl2/functions.api >> ../opengl2.1.h
done

cd -

for C in comp core
do
  for V in 3.0 3.1 3.2 3.3
  do
    cd gl/$V/$C/function
    rm ../../opengl$V-$C.h

    for F in *
    do
      echo "" >> ../../opengl$V-$C.h
      echo "/** @see $F */" >> ../../opengl$V-$C.h
      A=$(egrep "$F\(" ../../../../../list/gl3/functions.api)
      if [ -z "$A" ]
      then
        egrep "$F\(" ../../../../../list/gl2/functions.api >> ../../opengl$V-$C.h
      else
        echo "$A" >> ../../opengl$V-$C.h
      fi
    done

    cd -
  done
done