#!/usr/bin/python

import os

root = os.path.join('..', 'specs')
for v in ['2.1', '3.0', '3.1', '3.2', '3.3', '4.0', '4.1', '4.2', '4.3']:
  if v == '2.1':
    comps = ['']
  else:
    comps = ['core', 'comp']

  for c in comps:
    if v == '2.1':
      source = os.path.join('gl', v)
      target = os.path.join(root, 'gl%s' % v, 'index')
    else:
      source = os.path.join('gl', v, c)
      target = os.path.join(root, 'gl%s' % v, 'index.%s' % c)

    functions = os.listdir(os.path.join(source, 'function'))
    with open('%s.functions' % target, 'w') as output:
      for f in sorted(functions):
        print >>output, f

    if os.path.exists(os.path.join(source, 'constant')):
      constants = os.listdir(os.path.join(source, 'constant'))
      with open('%s.constants' % target, 'w') as output:
        for c in sorted(constants):
          print >>output, c
